-- Crear tabla ROL
CREATE TABLE IF NOT EXISTS ROL (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255)
);

-- Insertar datos en tabla ROL
INSERT INTO ROL (NOMBRE) VALUES ('ROLE_ADMIN');
INSERT INTO ROL (NOMBRE) VALUES ('ROLE_USER');

-- Crear tabla USUARIO
CREATE TABLE IF NOT EXISTS USUARIO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(255),
    PASSWORD VARCHAR(255),
    ROL_ID INT,
    FOREIGN KEY (ROL_ID) REFERENCES ROL(ID)
);

-- Crear tabla de relación entre USUARIO y ROL
CREATE TABLE IF NOT EXISTS usuario_rol (
    usuario_id INT AUTO_INCREMENT,
    rol_id INT,
    PRIMARY KEY (usuario_id, rol_id),
    FOREIGN KEY (usuario_id) REFERENCES USUARIO(ID),
    FOREIGN KEY (rol_id) REFERENCES ROL(ID)
);

-- Crear tabla ODONTOLOGO
CREATE TABLE IF NOT EXISTS ODONTOLOGO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    APELLIDO VARCHAR(255),
    NOMBRE VARCHAR(255),
    MATRICULA VARCHAR(255)
);

-- Crear tabla PACIENTE
CREATE TABLE IF NOT EXISTS PACIENTE (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRE VARCHAR(255),
    APELLIDO VARCHAR(255),
    DOMICILIO VARCHAR(255),
    DNI VARCHAR(255),
    FECHA_ALTA DATE
);

-- Crear tabla TURNO
CREATE TABLE IF NOT EXISTS TURNO (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_HORA TIMESTAMP,
    PACIENTE_ID INT,
    ODONTOLOGO_ID INT,
    FOREIGN KEY (PACIENTE_ID) REFERENCES PACIENTE(ID),
    FOREIGN KEY (ODONTOLOGO_ID) REFERENCES ODONTOLOGO(ID)
);


-- Insertar datos de ejemplo (puedes modificar estos datos según tus necesidades)
INSERT INTO USUARIO (ID, USERNAME, PASSWORD) VALUES (1, 'admin', 'adminpass');
INSERT INTO usuario_rol (usuario_id, rol_id) VALUES (1, 1);
INSERT INTO ODONTOLOGO (ID, APELLIDO, NOMBRE, MATRICULA) VALUES (1, 'Gomez', 'Juan', 'OD1234');
INSERT INTO PACIENTE (ID, NOMBRE, APELLIDO, DOMICILIO, DNI, FECHA_ALTA) VALUES (1, 'Perez', 'Ana', 'Calle 123', '12345678', '2023-01-01');
INSERT INTO TURNO (ID, FECHA_HORA, PACIENTE_ID, ODONTOLOGO_ID) VALUES (1, '2023-01-02 09:00:00', 1, 1);

